### ISSUE TITLE
Deixar o cabeçalho do menu-block igual dos blocos customizados

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/fflch-theme#12]

**Comment by thiagogomesverissimo** [comment]
Atualmente somente o bloco fica com título azul. Um menu posisionado como bloco não assume essa característica.

**Comment by ricardfo** [comment]
No meu teste um menu posicionado como bloco, ficou azul, agora se eu pedir para exibir o título do bloco com um menu posicionado daí não fica azul o titulo. Está correto isso? Ou entendi errado?
